{% set name = "buf" %}
{% set version = "1.51.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bufbuild/buf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 201b287802e3473cd0b8667f9049c02a0aac11eedaa1babcf9e6c37d9f4a2bf6

build:
  number: 0
  script:
    - go build -v -o $PREFIX/bin/buf ./cmd/buf                                              # [not win]
    - go build -v -o $PREFIX/bin/protoc-gen-buf-breaking ./cmd/protoc-gen-buf-breaking      # [not win]
    - go build -v -o $PREFIX/bin/protoc-gen-buf-lint ./cmd/protoc-gen-buf-lint              # [not win]
    - go install -v ./cmd/buf                           # [win]
    - go install -v ./cmd/protoc-gen-buf-breaking       # [win]
    - go install -v ./cmd/protoc-gen-buf-lint           # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - buf --version

about:
  home: https://buf.build/
  license: Apache-2.0
  license_file: LICENSE
  summary: A new way of working with Protocol Buffers.
  description: |
    Buf's goal is to shift API development toward a schema-driven paradigm and thus pave the way for a future
    in which APIs are defined in a way that service owners and clients can depend on.
  doc_url: https://docs.buf.build/introduction
  dev_url: https://github.com/bufbuild/buf

extra:
  recipe-maintainers:
    - mariusvniekerk
