{% set name = "buf" %}
{% set version = "1.55.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bufbuild/buf/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 01663475792aa851d4b3af16be9ec19d808cead673f986902343beed1a0063dd

build:
  number: 0
  script:
    - go build -v -o $PREFIX/bin/buf ./cmd/buf                                              # [not win]
    - go build -v -o $PREFIX/bin/protoc-gen-buf-breaking ./cmd/protoc-gen-buf-breaking      # [not win]
    - go build -v -o $PREFIX/bin/protoc-gen-buf-lint ./cmd/protoc-gen-buf-lint              # [not win]
    - go install -v ./cmd/buf                           # [win]
    - go install -v ./cmd/protoc-gen-buf-breaking       # [win]
    - go install -v ./cmd/protoc-gen-buf-lint           # [win]

requirements:
  build:
    - {{ compiler('go') }}

test:
  commands:
    - buf --version

about:
  home: https://buf.build/
  license: Apache-2.0
  license_file: LICENSE
  summary: A new way of working with Protocol Buffers.
  description: |
    Buf's goal is to shift API development toward a schema-driven paradigm and thus pave the way for a future
    in which APIs are defined in a way that service owners and clients can depend on.
  doc_url: https://docs.buf.build/introduction
  dev_url: https://github.com/bufbuild/buf

extra:
  recipe-maintainers:
    - mariusvniekerk
